### ISSUE TITLE
remove .DS_Store file in src

### ISSUE THREAD

**Issue by RLesur** [InseeFr/Impala#2]
#1 has merged [src/.DS_Store](https://github.com/InseeFr/Impala/blob/main/src/.DS_Store) into `main`.  
`.DS_Store` files should not be added to a git repository.

Please, can you remove it and add `.DS_Store` to the `.gitignore` file?

**Comment by BulotF** [comment]
Done : https://github.com/InseeFr/Impala/pull/3

Thank you for your vigilance
