### ISSUE TITLE
Déférencement des uris

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Impala#38]
Pouvoir envoyer une description de la ressource lorsque l’uri est mise dans un navigateur

**Comment by ChristopheYon** [comment]
Est-ce que ce n'est pas déjà fait ?

**Comment by EmmanuelDemey** [comment]
@JeromeMBourgeois  ?

**Comment by JeromeMBourgeois** [comment]
@EmmanuelDemey  effectivement c'est déjà fait.
