### ISSUE TITLE
Refaire la demande à l'infra pour la mise en production de Impala

### ISSUE THREAD

**Issue by EmmanuelDemey** [InseeFr/Impala#39]

**Comment by JeromeMBourgeois** [comment]
disponible pour recette sur l'url suivante : http://test-rdf.insee.fr/sparql/

**Comment by ChristopheYon** [comment]
Ça semble bien fonctionner comme endpoint, y compris les règles CORS qui vont bien. 
Et ça fonctionne bien en interactif  sur http://test-rdf.insee.fr/sparql/  
Mais ça coince si on tente de passer des requêtes depuis https://test-rdf.insee.fr/sparql/  (donc depuis la page en https). Or si on saisit "test-rdf.insee.fr/sparql" dans le navigateur, Firefox ouvre bien la page en http alors que Edge l'ouvre en https. Donc ça marche dans le premier cas et pas dans le second.

**Comment by JeromeMBourgeois** [comment]
Bon, j'ai mis du https partout. Je te laisse me dire si cela convient.
